[ids]
*

[main]
# Tap j and k together for escape
j+k = esc

# Tap f and d together for backspace
f+d = backspace

# Tap d or k and space together and:
# * Release all for one-shot shift.
# * Keep holding space for shift.
d+space = oneshot(shift)
k+space = oneshot(shift)
