[ids]
*

[main]
# Home row modifier keys (overload hold -> mod, tap -> letter)
a = overload(control, a)
s = overload(alt, s)
d = overload(meta, d)
f = overload(shift, f)

j = overload(shift, j)
k = overload(meta, k)
l = overload(alt, l)
semicolon = overload(control, ;)
